export const LOOP_READ_TOOLS = [
  "loop_tool_inventory",
  "loop_get_me",
  "loop_get_user",
  "loop_get_users_by_ids",
  "loop_get_users_by_usernames",
  "loop_get_user_statuses_by_ids",
  "loop_get_team",
  "loop_get_team_membership",
  "loop_list_teams",
  "loop_list_team_public_channels",
  "loop_list_team_members",
  "loop_resolve_team_by_name",
  "loop_list_my_team_unreads",
  "loop_get_my_channel_mention_state",
  "loop_list_team_unread_mentions",
  "loop_list_team_mentions",
  "loop_list_all_unread_mentions",
  "loop_list_all_mentions",
  "loop_get_channel",
  "loop_list_my_team_channels",
  "loop_get_channel_stats",
  "loop_list_team_channel_memberships",
  "loop_list_channel_members",
  "loop_get_channel_membership",
  "loop_get_post",
  "loop_list_channel_posts",
  "loop_list_pinned_posts",
  "loop_get_post_thread",
  "loop_resolve_channel_by_name",
  "loop_resolve_user_by_username",
] as const;

export const LOOP_WRITE_TOOLS = [
  "loop_create_direct_channel",
  "loop_create_group_channel",
  "loop_create_post",
  "loop_reply_to_post",
  "loop_update_post",
  "loop_delete_post",
] as const;

export const LOOP_TOOL_CATALOG = [
  { name: "loop_tool_inventory", kind: "read", implementation: "implemented" },
  { name: "loop_get_me", kind: "read", implementation: "implemented" },
  { name: "loop_get_user", kind: "read", implementation: "implemented" },
  { name: "loop_get_users_by_ids", kind: "read", implementation: "implemented" },
  {
    name: "loop_get_users_by_usernames",
    kind: "read",
    implementation: "implemented",
  },
  {
    name: "loop_get_user_statuses_by_ids",
    kind: "read",
    implementation: "implemented",
  },
  { name: "loop_get_team", kind: "read", implementation: "implemented" },
  {
    name: "loop_get_team_membership",
    kind: "read",
    implementation: "implemented",
  },
  { name: "loop_list_teams", kind: "read", implementation: "implemented" },
  {
    name: "loop_list_team_public_channels",
    kind: "read",
    implementation: "implemented",
  },
  { name: "loop_list_team_members", kind: "read", implementation: "implemented" },
  {
    name: "loop_resolve_team_by_name",
    kind: "read",
    implementation: "implemented",
  },
  {
    name: "loop_list_my_team_unreads",
    kind: "read",
    implementation: "implemented",
  },
  {
    name: "loop_get_my_channel_mention_state",
    kind: "read",
    implementation: "implemented",
  },
  {
    name: "loop_list_team_unread_mentions",
    kind: "read",
    implementation: "implemented",
  },
  {
    name: "loop_list_team_mentions",
    kind: "read",
    implementation: "implemented",
  },
  {
    name: "loop_list_all_unread_mentions",
    kind: "read",
    implementation: "implemented",
  },
  {
    name: "loop_list_all_mentions",
    kind: "read",
    implementation: "implemented",
  },
  { name: "loop_get_channel", kind: "read", implementation: "implemented" },
  {
    name: "loop_list_my_team_channels",
    kind: "read",
    implementation: "implemented",
  },
  { name: "loop_get_channel_stats", kind: "read", implementation: "implemented" },
  {
    name: "loop_list_team_channel_memberships",
    kind: "read",
    implementation: "implemented",
  },
  {
    name: "loop_list_channel_members",
    kind: "read",
    implementation: "implemented",
  },
  {
    name: "loop_get_channel_membership",
    kind: "read",
    implementation: "implemented",
  },
  { name: "loop_get_post", kind: "read", implementation: "implemented" },
  { name: "loop_list_channel_posts", kind: "read", implementation: "implemented" },
  { name: "loop_list_pinned_posts", kind: "read", implementation: "implemented" },
  { name: "loop_get_post_thread", kind: "read", implementation: "implemented" },
  {
    name: "loop_resolve_channel_by_name",
    kind: "read",
    implementation: "implemented",
  },
  {
    name: "loop_resolve_user_by_username",
    kind: "read",
    implementation: "implemented",
  },
  {
    name: "loop_create_direct_channel",
    kind: "write",
    implementation: "implemented",
  },
  {
    name: "loop_create_group_channel",
    kind: "write",
    implementation: "implemented",
  },
  { name: "loop_create_post", kind: "write", implementation: "implemented" },
  { name: "loop_reply_to_post", kind: "write", implementation: "implemented" },
  { name: "loop_update_post", kind: "write", implementation: "implemented" },
  { name: "loop_delete_post", kind: "write", implementation: "implemented" },
] as const;
